# Generated by Django 4.0.6 on 2022-07-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='acronym',
            field=models.CharField(default='USD', max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(default='US Dollar', max_length=30, unique=True),
        ),
    ]
