# Generated by Django 4.0.6 on 2022-07-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='dealer',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='balance',
            name='user',
            field=models.CharField(default='', max_length=30),
        ),
    ]
