# Generated by Django 4.0.6 on 2022-07-28 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0001_initial'),
        ('trades', '0002_alter_balance_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='dealer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dealer.dealer'),
        ),
    ]
