# Generated by Django 4.0.6 on 2022-08-01 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('dealer', '0003_dealercar_price'),
        ('trades', '0004_alter_balance_dealer_alter_balance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealer_balance', to='dealer.dealer'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_balance', to='users.userprofile'),
        ),
    ]
