# Generated by Django 4.0.6 on 2022-08-01 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0006_alter_balance_created_at_alter_balance_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='user',
            new_name='customer',
        ),
    ]
