# Generated by Django 4.0.6 on 2022-08-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0007_rename_user_balance_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
