# Generated by Django 4.0.6 on 2022-08-03 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0007_alter_currency_acronym_alter_currency_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='name',
        ),
    ]
