# Generated by Django 4.0.6 on 2022-08-03 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0008_remove_currency_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='acronym',
            new_name='name',
        ),
    ]
