# Generated by Django 4.0.6 on 2022-07-22 08:44

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('lastUpdate', models.DateTimeField()),
                ('instanceTime', models.TimeField()),
                ('amount', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('lastUpdate', models.DateTimeField()),
                ('instanceTime', models.TimeField()),
                ('price', models.IntegerField(default=0)),
                ('model', models.CharField(max_length=60)),
                ('amount', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShowRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('lastUpdate', models.DateTimeField()),
                ('instanceTime', models.TimeField()),
                ('name', models.CharField(max_length=30)),
                ('location', models.IntegerField(default=0)),
                ('customers', models.TextField(default='')),
                ('history', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('lastUpdate', models.DateTimeField()),
                ('instanceTime', models.TimeField()),
                ('is_customer', models.BooleanField(default=False)),
                ('is_vendor', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('lastUpdate', models.DateTimeField()),
                ('instanceTime', models.TimeField()),
                ('foundationYear', models.DateTimeField()),
                ('customersAmount', models.IntegerField(default=0)),
                ('location', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('lastUpdate', models.DateTimeField()),
                ('instanceTime', models.TimeField()),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('discount', models.IntegerField(default=0)),
                ('dealer', models.ManyToManyField(to='users.showroom')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('lastUpdate', models.DateTimeField()),
                ('instanceTime', models.TimeField()),
                ('maxPrice', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('lastUpdate', models.DateTimeField()),
                ('instanceTime', models.TimeField()),
                ('history', models.TextField(default='')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('lastUpdate', models.DateTimeField()),
                ('instanceTime', models.TimeField()),
                ('acronym', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=30)),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.balance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarSpecifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('lastUpdate', models.DateTimeField()),
                ('instanceTime', models.TimeField()),
                ('engine', models.CharField(max_length=60)),
                ('horsepower', models.IntegerField(default=0)),
                ('torque', models.IntegerField(default=0)),
                ('transmission', models.TextField()),
                ('overclocking', models.IntegerField(default=0)),
                ('car', models.ManyToManyField(to='users.car')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='car',
            name='dealer',
            field=models.ManyToManyField(to='users.showroom'),
        ),
        migrations.AddField(
            model_name='car',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.offer'),
        ),
        migrations.AddField(
            model_name='car',
            name='vendor',
            field=models.ManyToManyField(to='users.vendor'),
        ),
        migrations.AddField(
            model_name='balance',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.showroom'),
        ),
        migrations.AddField(
            model_name='balance',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
    ]
