# Generated by Django 4.0.6 on 2022-07-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_vendor',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile',
            field=models.BooleanField(choices=[(1, 'none'), (2, 'customer'), (3, 'vendor')], default=1),
        ),
    ]
