# Generated by Django 4.0.6 on 2022-07-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cars_amount',
            field=models.IntegerField(default=0),
        ),
    ]
