# Generated by Django 4.0.6 on 2022-07-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_is_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile',
            field=models.IntegerField(choices=[(1, 'none'), (2, 'customer'), (3, 'vendor')], default=1),
        ),
    ]
