# Generated by Django 4.0.6 on 2022-08-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile',
            field=models.CharField(choices=[('none', 'NONE'), ('customer', 'CUSTOMER'), ('vendor', 'VENDOR'), ('dealer', 'DEALER')], default='none', max_length=8),
        ),
    ]
