# Generated by Django 4.0.6 on 2022-07-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile',
            field=models.CharField(choices=[('n', 'none'), ('c', 'customer'), ('v', 'vendor')], default='n', max_length=1),
        ),
    ]
