# Generated by Django 4.0.6 on 2022-07-28 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_amount'),
        ('users', '0003_remove_userprofile_car_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_userprofilecar', to='cars.car')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='balance',
        ),
        migrations.DeleteModel(
            name='history_userprofile_car',
        ),
        migrations.AddField(
            model_name='userprofilecar',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_userprofilecar', to='users.userprofile'),
        ),
    ]
