# Generated by Django 4.0.6 on 2022-08-03 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_alter_userprofile_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilecar',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
