# Generated by Django 4.0.6 on 2022-07-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0001_initial'),
        ('users', '0004_alter_userprofile_profile'),
        ('cars', '0002_rename_carspecifications_carspecification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='dealer',
            field=models.ManyToManyField(blank=True, to='dealer.dealer'),
        ),
        migrations.AlterField(
            model_name='car',
            name='user',
            field=models.ManyToManyField(blank=True, to='users.userprofile'),
        ),
    ]
