# Generated by Django 4.0.6 on 2022-07-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_remove_car_dealer_remove_car_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carspecification',
            name='car',
        ),
        migrations.AddField(
            model_name='car',
            name='specification',
            field=models.ManyToManyField(to='cars.carspecification'),
        ),
    ]
