# Generated by Django 4.0.6 on 2022-08-03 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofilecar_price_alter_userprofile_user'),
        ('dealer', '0002_alter_dealer_profile'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_customer_order', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='dealerorder',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_dealer_order', to='dealer.dealer'),
        ),
    ]
