# Generated by Django 4.0.6 on 2022-07-28 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealer', '__first__'),
        ('users', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordervendortodealer',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_order_vendor_to_dealer', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='orderdealertocustomer',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_order_dealer_to_customer', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='orderdealertocustomer',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_order_dealer_to_customer', to='dealer.dealer'),
        ),
    ]
