# Generated by Django 4.0.6 on 2022-07-29 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0003_dealercar_price'),
        ('cars', '0003_remove_car_price'),
        ('users', '0001_initial'),
        ('orders', '0002_ordercustomertodealer_orderdealertovendor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('last_update', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('price', models.FloatField(default=0.0)),
                ('amount', models.IntegerField(default=0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_customer_order', to='cars.car')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_customer_order', to='users.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DealerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('last_update', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('price', models.FloatField(default=0.0)),
                ('amount', models.IntegerField(default=0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_dealer_order', to='cars.car')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_dealer_order', to='dealer.dealer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='orderdealertovendor',
            name='car',
        ),
        migrations.RemoveField(
            model_name='orderdealertovendor',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='orderdealertovendor',
            name='sender',
        ),
        migrations.DeleteModel(
            name='OrderCustomerToDealer',
        ),
        migrations.DeleteModel(
            name='OrderDealerToVendor',
        ),
    ]
