# Generated by Django 4.0.6 on 2022-08-01 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_customerorder_dealerorder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerorder',
            old_name='sender',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='dealerorder',
            old_name='sender',
            new_name='dealer',
        ),
    ]
