# Generated by Django 4.0.6 on 2022-08-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_customerorder_amount_alter_dealerorder_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dealerorder',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
