# Generated by Django 4.0.6 on 2022-07-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='history',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='profile',
        ),
        migrations.AlterField(
            model_name='dealer',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
