# Generated by Django 4.0.6 on 2022-07-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '__first__'),
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='profile',
            field=models.ManyToManyField(blank=True, to='users.userprofile'),
        ),
    ]
