# Generated by Django 4.0.6 on 2022-07-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_remove_car_dealer_remove_car_user'),
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='car',
            field=models.ManyToManyField(blank=True, to='cars.car'),
        ),
    ]
