# Generated by Django 4.0.6 on 2022-07-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('dealer', '0002_dealer_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='customers',
        ),
        migrations.AddField(
            model_name='dealer',
            name='profile',
            field=models.ManyToManyField(blank=True, to='users.userprofile'),
        ),
    ]
