# Generated by Django 4.0.6 on 2022-07-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0002_remove_dealer_history_remove_dealer_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealercar',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
