# Generated by Django 4.0.6 on 2022-07-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0003_remove_dealer_customers_dealer_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='cars_amount',
            field=models.IntegerField(default=0),
        ),
    ]
