# Generated by Django 4.0.6 on 2022-07-28 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_amount'),
        ('dealer', '0004_dealer_cars_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='car',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='cars_amount',
        ),
        migrations.CreateModel(
            name='history_dealer_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('dealer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.dealer')),
            ],
        ),
    ]
